title: Game Dev Blog
description: >-
  Game dev ideas that are not fit for human consumption, but we want to write them down somewhere.

remote_theme: "jekyll/minima@1e8a445"

plugins:
  - jekyll-remote-theme  

